name: Maven JavaFX JLink Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    name: Build and Release JavaFX JLink ZIP
    permissions:
      contents: write  # Required to create release and upload assets
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Get version from pom.xml
      id: get_version
      run: |
        version=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
        echo "version=$version" >> "$GITHUB_OUTPUT"

    - name: Install QEMU and build for ARM64
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu22.04
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        install: |
          apt-get update
          apt-get install -y maven zip
        run: |
          mvn -B javafx:jlink

    - name: Create GitHub Release and upload app.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG="v${{ steps.get_version.outputs.version }}"
        gh release create "$TAG" target/app.zip \
          --title "Release $TAG" \
          --notes "Auto-generated release for version $TAG"
