name: JavaFX Nightly Build

on:
  push:
    branches:
      - main

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    name: Nightly JavaFX JLink Build
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build on ARM64 with QEMU
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu22.04
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        install: |
          apt-get update
          apt-get install -y maven
        run: |
          mvn -B javafx:jlink

    - name: Get Date Tag
      id: tag
      run: |
        echo "date_tag=nightly-$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

    - name: Create GitHub Nightly Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG=${{ steps.tag.outputs.date_tag }}
        gh release create "$TAG" target/app.zip \
          --title "Nightly Build - $TAG" \
          --notes "This is an automated nightly build of the latest commit to main."
